### PR TITLE
Add type linting

### PR DESCRIPTION
**Pull request by barmac**
This is a proposal of how we could use TypeScript in this project as a linter. It already [allowed to detect a bug](https://github.com/nikku/merge-me/commit/6206ec15d0b34c34acdc50fda3ae8cd6ce928095) and might be useful in case of silently released breaking changes in probot/octokit.

There are still a few problems to fix, but I want to share current progress.

### CODE REVIEW

**Comment by nikku** [comment]
Great stuff :tada:

**Comment by barmac** [comment]
So the problem with expected `Promise<void>` is actually a TypeScript bug: https://github.com/microsoft/TypeScript/issues/12871

**Comment by nikku** [comment]
OMG TYPE SCRIPT! :octopus:

**Comment by nikku** [comment]
You gotta fix one issue and introduce another one I guess. That is how it goes.

**Comment by barmac** [comment]
What's funny is that [a probot example from the project's readme ](https://github.com/probot/probot#how-it-works) does not compile in TypeScript 🗡️

**Comment by barmac** [comment]
I added `@ts-ignore`s which apply only to the callback, so they shouldn't really expose us to any errors. [Current build](https://travis-ci.com/github/nikku/merge-me/builds/170085633) reveals now two problems which might potentially be bugs in the app, at least if the types don't lie.

**Comment by barmac** [comment]
I think the `pull_request` type error leads to unexpected behavior, although the app still works correctly. I debugged `merge-me` with a test repository indeed the fields mentioned in the check function don't exist on the passed object.

image

As a consequence, a draft pull request passes all the way to https://github.com/nikku/merge-me/blob/master/lib/core.js#L321. It passes [the `pull_request.draft` check](https://github.com/nikku/merge-me/blob/master/lib/core.js#L370).

**Comment by barmac** [comment]
I was able to resolve problems described above thanks to union types. So only the `org` problem persists. I need to debug it yet.

**Comment by nikku** [comment]
That is great work overall already. :clap:

**Comment by nikku** [comment]
Regarding the org thing, this seems to be all according to documentation at least: https://octokit.github.io/rest.js/v16#teams-list-members-in-org

**Comment by barmac** [comment]
Thanks! Actually, we are using params for `listMembersInOrg` (doc you linked) while using [`listMembers` API:](https://octokit.github.io/rest.js/v16#teams-list-members)

```javascript
    const {
      data: members
    } = await GithubApi(context).teams.listMembers({
      org,
      team_id: id
    });
```

...which is deprecated. Let's try out `listMembersInOrg` instead.

**Comment by nikku** [comment]
It actually surfaced another potential improvement.

Listing all teams in an organization is potentially dangerous (huge list!) and not needed, after all.

I've renamed the API usage here: https://github.com/nikku/merge-me/commit/11321601ea94a5799c8b2e5c7cc4dfdc37bbaf6d

You could pull the commits from that branch onto your PR to see it go green.

**Comment by nikku** [comment]
I'll need to setup a test org to see this working live though before merging.

**Comment by barmac** [comment]
Great! Your commit is now on my branch. I'm going to test it on my machine too.

**Comment by nikku** [comment]
There is another bug that is still _in_ the code base, despite extensive typing:

The `check_suite.completed` event only embeds a what I would call _shallow_ version of the referenced pull requests: https://developer.github.com/webhooks/event-payloads/#check_suite

We, however deal with the PR as if it was the full thing (i.e. what is returned by https://developer.github.com/webhooks/event-payloads/#pull_request_review).

I'll likely fix it by fetching the full PR on each check_suite.completed event.

**Comment by nikku** [comment]
Regarding typings, it feels odd that they did not catch https://github.com/nikku/merge-me/pull/14#issuecomment-640119755.

With the `@ts-ignore` we have essentially zero typing in the bot script (https://github.com/nikku/merge-me/blob/master/lib/bot.js).

My proposal would be in this case to explicitly type the callback functions, i.e.

```
app.on('foo', 
/**
 * @param FOOBAR
 */
  function(foobar) {
  
  }
);
```

(If that or a similar thing would work.)

**Comment by barmac** [comment]
Regarding the _shallow PR_ problem, I tried to fix it via https://github.com/nikku/merge-me/pull/14/commits/bf8d286b6e074953b4d0c96d82db70c83297d5b2, but of course we can just make sure to use the Webhook PR all the time.

Cf. https://github.com/nikku/merge-me/pull/14#issuecomment-640081142

**Comment by nikku** [comment]
I've worked on https://github.com/nikku/merge-me/pull/14#issuecomment-640119755 via https://github.com/nikku/merge-me/pull/15 and https://github.com/nikku/merge-me/pull/15/commits/f7fa55c0eece52a25b5af372312e269531f4d28b.

That should make overall typing of this thing simpler.

**Comment by nikku** [comment]
(It also improves the robustness of the bot.)

**Comment by nikku** [comment]
I can also investigate that typing thing and complete it myself. Looks promising.

Still find myself struggling with "where to get those types from" though :wink:.

**Comment by barmac** [comment]
Indeed, it's not easy. I rely mostly on the compiler complaints.

**Comment by barmac** [comment]
Rebased on master.

**Comment by barmac** [comment]
> So the problem with expected `Promise<void>` is actually a TypeScript bug: [microsoft/TypeScript#12871](https://github.com/microsoft/TypeScript/issues/12871)

I fixed this via https://github.com/nikku/merge-me/pull/14/commits/bf94dc793cb7fadd6f3c8c1c96a59f4e2c97a725. There is a problem with the context, though.

**Comment by nikku** [comment]
Thanks for your work :clap:.

I'll fix the remaining issues outside this PR.

**Comment by barmac** [comment]
Happy to help :)

**Pull request merged**
